"""
Django settings for core_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e55!khb8+%1ek&cf(fihrl-5myuea$5-wlrf+l1j7w6-t13x_n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis', # Thư viện xử lý không gian PostGIS
    'pho_app',            # App vừa tạo
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', # Dùng engine GIS
        'NAME': 'Quanlypho',          # Đổi thành tên DB của bạn
        'USER': 'postgres',       # Đổi thành username DB của bạn
        'PASSWORD': '123',   # Đổi thành mật khẩu DB của bạn
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/assets/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'dist', 'assets')]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

import os

# --- Cấu hình GDAL/GEOS cho môi trường Windows ---
if os.name == 'nt':
    # 1. Đường dẫn tới thư mục bin PostgreSQL có cài PostGIS/GDAL.
    POSTGIS_BIN = r'C:\Program Files\PostgreSQL\17\bin'
    
    # 2. Thêm thư mục bin vào PATH của hệ điều hành
    os.environ['PATH'] = POSTGIS_BIN + os.pathsep + os.environ['PATH']
    
    # 3. Kích hoạt tính năng tải DLL của Python (rất quan trọng với Python >= 3.8)
    if hasattr(os, 'add_dll_directory'):
        try:
            os.add_dll_directory(POSTGIS_BIN)
        except Exception:
            pass
            
    # 4. Trỏ trực tiếp tới file GDAL và GEOS
    GDAL_LIBRARY_PATH = os.path.join(POSTGIS_BIN, 'libgdal-35.dll')
    GEOS_LIBRARY_PATH = os.path.join(POSTGIS_BIN, 'libgeos_c.dll')
# ------------------------------------------------

AUTH_USER_MODEL = 'pho_app.User'