# Generated by Django 6.1.1 on 2026-10-04 09:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BROTH', 'Nước dùng (Béo/Trong)'), ('VEGGIE', 'Rau / Giá (Không hành/Giá chín...)'), ('NOODLE', 'Bánh phở (Nhiều/Ít bánh)')], max_length=20, verbose_name='Phân loại tùy chọn')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tùy chọn (VD: Không hành)')),
            ],
            options={
                'verbose_name': 'Tùy chọn miễn phí',
                'verbose_name_plural': 'Danh mục Tùy chọn miễn phí',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nguyên liệu (VD: Bánh phở, Thịt bò)')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính (kg, gram, lít...)')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số lượng tồn hiện tại')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ngưỡng cảnh báo hết hàng')),
                ('ingredient_image', models.ImageField(blank=True, null=True, upload_to='ingredients/', verbose_name='Ảnh minh họa')),
            ],
            options={
                'verbose_name': 'Nguyên liệu kho',
                'verbose_name_plural': 'Danh mục Nguyên liệu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên món (VD: Phở Tái)')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá gốc (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn kinh doanh')),
                ('image_primary', models.ImageField(upload_to='menu_items/', verbose_name='Ảnh đại diện chính')),
                ('image_detail_1', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Ảnh chi tiết 1 (Cận cảnh)')),
                ('image_detail_2', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Ảnh chi tiết 2 (Không gian/Góc rộng)')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Danh mục Món ăn',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='Số bàn')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Trống'), ('OCCUPIED', 'Đang có khách'), ('CLEANING', 'Đang dọn dẹp')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái bàn')),
                ('qr_code_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn QR')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Ảnh mã QR')),
            ],
            options={
                'verbose_name': 'Bàn ăn',
                'verbose_name_plural': 'Danh sách Bàn ăn',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Topping (VD: Trứng chần)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá tính thêm (VNĐ)')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='toppings/', verbose_name='Ảnh minh họa nhỏ')),
            ],
            options={
                'verbose_name': 'Topping tính phí',
                'verbose_name_plural': 'Danh mục Topping',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('STAFF', 'Thu ngân / Điều phối'), ('KITCHEN', 'Bếp'), ('ADMIN', 'Quản lý')], default='CUSTOMER', max_length=20, verbose_name='Vai trò')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất bán (Tự động)'), ('ADJUST', 'Điều chỉnh / Khấu hao hư hỏng')], max_length=20, verbose_name='Loại giao dịch')),
                ('quantity_changed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng thay đổi (+/-)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pho_app.ingredient', verbose_name='Nguyên liệu')),
            ],
            options={
                'verbose_name': 'Biến động kho',
                'verbose_name_plural': 'Lịch sử Kho',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Tại bàn'), ('DELIVERY', 'Giao tận nơi'), ('QUEUE_CART', 'Giỏ hàng chờ vào bàn')], default='DINE_IN', max_length=20, verbose_name='Loại đơn')),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('VIETQR', 'Chuyển khoản VietQR')], default='VIETQR', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('order_status', models.CharField(choices=[('CART', 'Giỏ hàng tạm'), ('PENDING_KITCHEN', 'Đang gửi Bếp'), ('COOKING', 'Bếp đang làm'), ('READY', 'Đã xong (Chờ bưng/Giao)'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Đã hủy')], default='CART', max_length=20, verbose_name='Trạng thái đơn')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền món (VNĐ)')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ giao hàng')),
                ('customer_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Tọa độ GPS khách hàng (PostGIS)')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí giao hàng (VNĐ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pho_app.table', verbose_name='Bàn số')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('item_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá thời điểm đặt')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pho_app.menuitem', verbose_name='Món chính')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pho_app.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết món đặt',
                'verbose_name_plural': 'Chi tiết các món đặt',
            },
        ),
        migrations.CreateModel(
            name='OrderItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pho_app.customizationoption', verbose_name='Tùy chọn tick chọn')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='pho_app.orderitem', verbose_name='Món ăn')),
            ],
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, verbose_name='Số thứ tự (VD: P-015)')),
                ('status', models.CharField(choices=[('WAITING', 'Đang chờ'), ('CALLED', 'Đã gọi số'), ('SEATED', 'Đã vào bàn'), ('CANCELLED', 'Đã hủy')], default='WAITING', max_length=20, verbose_name='Trạng thái hàng đợi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian lấy số')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Số thứ tự xếp hàng',
                'verbose_name_plural': 'Danh sách Xếp hàng',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Định lượng hao phí/1 đơn vị bán')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pho_app.ingredient', verbose_name='Nguyên liệu hao phí')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='pho_app.menuitem', verbose_name='Dùng cho Món chính')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='pho_app.topping', verbose_name='Dùng cho Topping')),
            ],
            options={
                'verbose_name': 'Định lượng sản phẩm (BOM)',
                'verbose_name_plural': 'Công thức Định lượng kho',
            },
        ),
        migrations.CreateModel(
            name='OrderItemTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng topping')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pho_app.orderitem', verbose_name='Món ăn')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pho_app.topping', verbose_name='Topping')),
            ],
        ),
    ]
