# Generated by Django 6.1.1 on 2026-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('CUSTOMER', 'Khách hàng'),
                    ('STAFF', 'Thu ngân'),
                    ('KITCHEN', 'Bếp'),
                    ('ADMIN', 'Admin'),
                ],
                default='CUSTOMER',
                max_length=20,
                verbose_name='Vai trò',
            ),
        ),
    ]