# Generated by Django 6.1.1 on 2026-10-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_detail_1',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_detail_2',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='Phở bò', max_length=100, verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả món ăn'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên khách (Khách lẻ)'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú tổng thể'),
        ),
        migrations.AddField(
            model_name='queueticket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên khách hàng'),
        ),
        migrations.AddField(
            model_name='queueticket',
            name='people_count',
            field=models.IntegerField(default=1, verbose_name='Số lượng người'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_primary',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Ảnh đại diện chính'),
        ),
    ]
