# Generated by Django 6.1.1 on 2026-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_app', '0003_repair_menu_detail_image_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Số bàn'),
        ),
    ]
