# Generated by Django 6.1.1 on 2026-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_app', '0004_alter_table_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên khách (nếu không đăng nhập)'),
        ),
    ]
