# Generated by Django 6.1.1 on 2026-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_app', '0005_order_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=4, verbose_name='Số lượng chỗ (Tô) tối đa'),
        ),
    ]
