# Generated by Django 6.1.1 on 2026-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_app', '0006_table_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cleared',
            field=models.BooleanField(default=False, verbose_name='Đã dọn bàn'),
        ),
    ]
